"""initial_schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-08 14:10:43.205906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('account_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('companies',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('employee_count_range', sa.String(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('account_config_profiles',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('target_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weights_ai_match', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weights_company_quality', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('collection_limits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notification_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('report_format_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt_template_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('account_id', 'config_version')
    )
    op.create_index('uq_account_config_profiles_one_active', 'account_config_profiles', ['account_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('company_scores',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('weight_profile_id', sa.Uuid(), nullable=True),
    sa.Column('rubric_version', sa.Integer(), nullable=False),
    sa.Column('score_total', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('score_total IS NULL OR (score_total >= 0 AND score_total <= 100)', name='ck_company_scores_score_total_range'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_company_scores_company_weight_profile', 'company_scores', ['company_id', 'weight_profile_id'], unique=False)
    op.create_index('uq_company_scores_custom', 'company_scores', ['company_id', 'weight_profile_id', 'rubric_version'], unique=True, postgresql_where=sa.text('weight_profile_id IS NOT NULL'))
    op.create_index('uq_company_scores_default', 'company_scores', ['company_id', 'rubric_version'], unique=True, postgresql_where=sa.text('weight_profile_id IS NULL'))
    op.create_table('job_postings',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('location_text', sa.String(), nullable=False),
    sa.Column('workplace_type', sa.Enum('On-site', 'Hybrid', 'Remote', name='workplace_type'), nullable=True),
    sa.Column('posted_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('easy_apply', sa.Boolean(), nullable=True),
    sa.Column('application_url', sa.Text(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index('ix_job_postings_content_hash', 'job_postings', ['content_hash'], unique=False)
    op.create_table('linkedin_sessions',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('encrypted_storage_state_ref', sa.Text(), nullable=True),
    sa.Column('session_status', sa.Enum('valid', 'expired', 'unknown', name='session_status'), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('run_locks',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lock_owner', sa.String(), nullable=True),
    sa.Column('lock_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('run_logs',
    sa.Column('run_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('trigger_type', sa.Enum('Scheduled', 'Manual', name='trigger_type'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('jobs_collected', sa.Integer(), nullable=False),
    sa.Column('jobs_filtered', sa.Integer(), nullable=False),
    sa.Column('jobs_new', sa.Integer(), nullable=False),
    sa.Column('jobs_closed', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Success', 'Partial', 'Failed', name='run_status'), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('collection_capped', sa.Boolean(), nullable=False),
    sa.CheckConstraint('jobs_closed >= 0', name='ck_run_logs_jobs_closed_non_negative'),
    sa.CheckConstraint('jobs_collected >= 0', name='ck_run_logs_jobs_collected_non_negative'),
    sa.CheckConstraint('jobs_filtered >= 0', name='ck_run_logs_jobs_filtered_non_negative'),
    sa.CheckConstraint('jobs_new >= 0', name='ck_run_logs_jobs_new_non_negative'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('ix_run_logs_account_started', 'run_logs', ['account_id', 'started_at'], unique=False)
    op.create_table('user_profiles',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('career_goals', sa.Text(), nullable=False),
    sa.Column('skills_summary', sa.Text(), nullable=False),
    sa.Column('preferences_dealbreakers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('evaluated_jobs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('ai_match_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('match_rationale', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('department_cluster', sa.Text(), nullable=True),
    sa.Column('filter_result_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('New', 'Seen', 'Updated', 'Closed', 'Excluded', name='job_status'), nullable=False),
    sa.Column('is_borderline', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('report_appearances_count', sa.Integer(), nullable=False),
    sa.Column('content_hash_at_evaluation', sa.Text(), nullable=False),
    sa.Column('config_version_used', sa.Integer(), nullable=False),
    sa.CheckConstraint('ai_match_score IS NULL OR (ai_match_score >= 0 AND ai_match_score <= 100)', name='ck_evaluated_jobs_ai_match_score_range'),
    sa.CheckConstraint('report_appearances_count >= 0', name='ck_evaluated_jobs_report_appearances_count_non_negative'),
    sa.ForeignKeyConstraint(['account_id', 'config_version_used'], ['account_config_profiles.account_id', 'account_config_profiles.config_version'], name='fk_evaluated_jobs_config_version'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.job_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'job_id', name='uq_evaluated_jobs_account_job')
    )
    op.create_index('ix_evaluated_jobs_account_status', 'evaluated_jobs', ['account_id', 'status'], unique=False)
    op.create_index('ix_evaluated_jobs_job_account', 'evaluated_jobs', ['job_id', 'account_id'], unique=False)
    op.create_table('reports',
    sa.Column('report_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('included_job_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('top_matches', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('config_snapshot_ref', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['account_id', 'config_snapshot_ref'], ['account_config_profiles.account_id', 'account_config_profiles.config_version'], name='fk_reports_config_snapshot'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['run_logs.run_id'], ),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_index('ix_evaluated_jobs_job_account', table_name='evaluated_jobs')
    op.drop_index('ix_evaluated_jobs_account_status', table_name='evaluated_jobs')
    op.drop_table('evaluated_jobs')
    op.drop_table('user_profiles')
    op.drop_index('ix_run_logs_account_started', table_name='run_logs')
    op.drop_table('run_logs')
    op.drop_table('run_locks')
    op.drop_table('linkedin_sessions')
    op.drop_index('ix_job_postings_content_hash', table_name='job_postings')
    op.drop_table('job_postings')
    op.drop_index('uq_company_scores_default', table_name='company_scores', postgresql_where=sa.text('weight_profile_id IS NULL'))
    op.drop_index('uq_company_scores_custom', table_name='company_scores', postgresql_where=sa.text('weight_profile_id IS NOT NULL'))
    op.drop_index('ix_company_scores_company_weight_profile', table_name='company_scores')
    op.drop_table('company_scores')
    op.drop_index('uq_account_config_profiles_one_active', table_name='account_config_profiles', postgresql_where=sa.text('is_active = true'))
    op.drop_table('account_config_profiles')
    op.drop_table('companies')
    op.drop_table('accounts')
    # ### end Alembic commands ###
    # NOT: Alembic'in autogenerate'i, native PostgreSQL ENUM tiplerini
    # create_table ile birlikte otomatik olusturur, ancak drop_table ile
    # birlikte otomatik SILMEZ (bilinen bir kisitlama - ayni tip birden
    # fazla tabloda kullanilabilecegi icin Alembic bunu varsayamaz). Bu
    # tipler burada tablolar silindikten SONRA elle temizlenir; aksi
    # halde bir sonraki "upgrade" "type already exists" hatasiyla basarisiz
    # olur (bu proje icin dogrulanmis bir davranis).
    sa.Enum(name='job_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='run_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='trigger_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='session_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='workplace_type').drop(op.get_bind(), checkfirst=True)
